(function(global){
  'use strict';
  const data=global.TRIAD_ENEMY_ANIMATION_DATA;
  if(!data?.byId)return;
  const pilot=data.byId.RIFT_M10;
  if(pilot)Object.assign(pilot,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M10/RIFT_M10_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=a7c57ce7435b',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M10_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M10/RIFT_M10_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shade=data.byId.SHADE_M01;
  if(shade)Object.assign(shade,{
    atlas:'assets/enemies/production_pilot_v6/SHADE_M01/SHADE_M01_PRODUCTION_PILOT_V6_GPU_FINAL.webp?v=6760838c0dd7',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'SHADE_M01_V6_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v6/SHADE_M01/SHADE_M01_PRODUCTION_PILOT_V6_GPU_FINAL_MANIFEST.json'
  });
  const ember=data.byId.EMBER_M13;
  if(ember)Object.assign(ember,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M13/EMBER_M13_PRODUCTION_PILOT_V4.webp?v=0d8fdc711bf5732e',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M13_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M13/EMBER_M13_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegis=data.byId.AEGIS_M13;
  if(aegis)Object.assign(aegis,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M13/AEGIS_M13_PRODUCTION_PILOT_V4.webp?v=745f918621781659',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M13_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M13/AEGIS_M13_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloom=data.byId.BLOOM_M13;
  if(bloom)Object.assign(bloom,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M13/BLOOM_M13_PRODUCTION_PILOT_V4.webp?v=4f5f45f2ab4ea57f',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M13_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M13/BLOOM_M13_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const volt=data.byId.VOLT_M13;
  if(volt)Object.assign(volt,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M13/VOLT_M13_PRODUCTION_PILOT_V4.webp?v=b04ed33b58849037',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M13_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M13/VOLT_M13_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftBoss=data.byId.RIFT_M13;
  if(riftBoss)Object.assign(riftBoss,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M13/RIFT_M13_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=2bb7acb37f07',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M13_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M13/RIFT_M13_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeBoss=data.byId.SHADE_M13;
  if(shadeBoss)Object.assign(shadeBoss,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M13/SHADE_M13_PRODUCTION_PILOT_V4.webp?v=69602036d1b129a4',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M13_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M13/SHADE_M13_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM14=data.byId.AEGIS_M14;
  if(aegisM14)Object.assign(aegisM14,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M14/AEGIS_M14_PRODUCTION_PILOT_V4.webp?v=c619c2ccadff9101',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M14_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M14/AEGIS_M14_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM14=data.byId.EMBER_M14;
  if(emberM14)Object.assign(emberM14,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M14/EMBER_M14_PRODUCTION_PILOT_V4.webp?v=c6f44bc606846ac2',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M14_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M14/EMBER_M14_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM14=data.byId.BLOOM_M14;
  if(bloomM14)Object.assign(bloomM14,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M14/BLOOM_M14_PRODUCTION_PILOT_V4.webp?v=60d5934466829631',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M14_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M14/BLOOM_M14_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM14=data.byId.VOLT_M14;
  if(voltM14)Object.assign(voltM14,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M14/VOLT_M14_PRODUCTION_PILOT_V4.webp?v=8f38da2747810127',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M14_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M14/VOLT_M14_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM14=data.byId.RIFT_M14;
  if(riftM14)Object.assign(riftM14,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M14/RIFT_M14_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=3942426a5fa3',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M14_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M14/RIFT_M14_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeM14=data.byId.SHADE_M14;
  if(shadeM14)Object.assign(shadeM14,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M14/SHADE_M14_PRODUCTION_PILOT_V4.webp?v=90146b725fb54f0f',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M14_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M14/SHADE_M14_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM15=data.byId.AEGIS_M15;
  if(aegisM15)Object.assign(aegisM15,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M15/AEGIS_M15_PRODUCTION_PILOT_V4.webp?v=5bfd89974490b45d',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M15_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M15/AEGIS_M15_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM15=data.byId.EMBER_M15;
  if(emberM15)Object.assign(emberM15,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M15/EMBER_M15_PRODUCTION_PILOT_V4.webp?v=0b2bf9de0d4bb90f',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M15_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M15/EMBER_M15_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM15=data.byId.BLOOM_M15;
  if(bloomM15)Object.assign(bloomM15,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M15/BLOOM_M15_PRODUCTION_PILOT_V4.webp?v=573d9b1f74ae04fe',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M15_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M15/BLOOM_M15_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM15=data.byId.VOLT_M15;
  if(voltM15)Object.assign(voltM15,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M15/VOLT_M15_PRODUCTION_PILOT_V4.webp?v=bb1c71960f7b487b',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M15_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M15/VOLT_M15_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM15=data.byId.RIFT_M15;
  if(riftM15)Object.assign(riftM15,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M15/RIFT_M15_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=c438be6f3d66',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M15_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M15/RIFT_M15_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeM15=data.byId.SHADE_M15;
  if(shadeM15)Object.assign(shadeM15,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M15/SHADE_M15_PRODUCTION_PILOT_V4.webp?v=ad7950c8ae27a419',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M15_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M15/SHADE_M15_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM12=data.byId.AEGIS_M12;
  if(aegisM12)Object.assign(aegisM12,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M12/AEGIS_M12_PRODUCTION_PILOT_V4.webp?v=13569d6205a54e64',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M12_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M12/AEGIS_M12_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM12=data.byId.EMBER_M12;
  if(emberM12)Object.assign(emberM12,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M12/EMBER_M12_PRODUCTION_PILOT_V4.webp?v=5f3899e584a97fec',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M12_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M12/EMBER_M12_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM12=data.byId.BLOOM_M12;
  if(bloomM12)Object.assign(bloomM12,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M12/BLOOM_M12_PRODUCTION_PILOT_V4.webp?v=64586e1f59f4b3a7',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M12_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M12/BLOOM_M12_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM12=data.byId.VOLT_M12;
  if(voltM12)Object.assign(voltM12,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M12/VOLT_M12_PRODUCTION_PILOT_V4.webp?v=bd9f6a38bcd404bc',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M12_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M12/VOLT_M12_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM12=data.byId.RIFT_M12;
  if(riftM12)Object.assign(riftM12,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M12/RIFT_M12_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=ef8d52e89aa9',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M12_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M12/RIFT_M12_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeM12=data.byId.SHADE_M12;
  if(shadeM12)Object.assign(shadeM12,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M12/SHADE_M12_PRODUCTION_PILOT_V4.webp?v=f6b717d5b9531bfe',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M12_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M12/SHADE_M12_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM11=data.byId.AEGIS_M11;
  if(aegisM11)Object.assign(aegisM11,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M11/AEGIS_M11_PRODUCTION_PILOT_V4.webp?v=5716d9b99500c54c',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M11_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M11/AEGIS_M11_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM11=data.byId.EMBER_M11;
  if(emberM11)Object.assign(emberM11,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M11/EMBER_M11_PRODUCTION_PILOT_V4.webp?v=a87736b238803f3f',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M11_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M11/EMBER_M11_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM11=data.byId.BLOOM_M11;
  if(bloomM11)Object.assign(bloomM11,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M11/BLOOM_M11_PRODUCTION_PILOT_V4.webp?v=aa3c9bc6ed5b79a2',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M11_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M11/BLOOM_M11_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM11=data.byId.VOLT_M11;
  if(voltM11)Object.assign(voltM11,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M11/VOLT_M11_PRODUCTION_PILOT_V4.webp?v=1b829b32d6ec18a7',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M11_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M11/VOLT_M11_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM11=data.byId.RIFT_M11;
  if(riftM11)Object.assign(riftM11,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M11/RIFT_M11_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=c20707cc4f1f',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M11_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M11/RIFT_M11_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeM11=data.byId.SHADE_M11;
  if(shadeM11)Object.assign(shadeM11,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M11/SHADE_M11_PRODUCTION_PILOT_V4.webp?v=7a3b80bc7aa9d20b',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M11_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M11/SHADE_M11_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM10=data.byId.AEGIS_M10;
  if(aegisM10)Object.assign(aegisM10,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M10/AEGIS_M10_PRODUCTION_PILOT_V4.webp?v=36726ee75dbb7dc5',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M10_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M10/AEGIS_M10_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM10=data.byId.EMBER_M10;
  if(emberM10)Object.assign(emberM10,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M10/EMBER_M10_PRODUCTION_PILOT_V4.webp?v=c4f1ccbf539e1322',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M10_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M10/EMBER_M10_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM10=data.byId.BLOOM_M10;
  if(bloomM10)Object.assign(bloomM10,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M10/BLOOM_M10_PRODUCTION_PILOT_V4.webp?v=156cdc71040ee94a',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M10_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M10/BLOOM_M10_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM10=data.byId.VOLT_M10;
  if(voltM10)Object.assign(voltM10,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M10/VOLT_M10_PRODUCTION_PILOT_V4.webp?v=ac80a7a0641d058b',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M10_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M10/VOLT_M10_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const shadeM10=data.byId.SHADE_M10;
  if(shadeM10)Object.assign(shadeM10,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M10/SHADE_M10_PRODUCTION_PILOT_V4.webp?v=67a42dcc43218260',
    frameWidth:420,
    frameHeight:420,
    columns:6,
    rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M10_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M10/SHADE_M10_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM09=data.byId.AEGIS_M09;
  if(aegisM09)Object.assign(aegisM09,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M09/AEGIS_M09_PRODUCTION_PILOT_V4.webp?v=066965cd32ee9154',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M09_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M09/AEGIS_M09_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM09=data.byId.EMBER_M09;
  if(emberM09)Object.assign(emberM09,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M09/EMBER_M09_PRODUCTION_PILOT_V4.webp?v=e16ce5f7b1b098a6',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M09_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M09/EMBER_M09_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM09=data.byId.BLOOM_M09;
  if(bloomM09)Object.assign(bloomM09,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M09/BLOOM_M09_PRODUCTION_PILOT_V4.webp?v=f931443010432654',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M09_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M09/BLOOM_M09_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM09=data.byId.VOLT_M09;
  if(voltM09)Object.assign(voltM09,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M09/VOLT_M09_PRODUCTION_PILOT_V4.webp?v=47a5e62d79007dff',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M09_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M09/VOLT_M09_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM09=data.byId.RIFT_M09;
  if(riftM09)Object.assign(riftM09,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M09/RIFT_M09_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=7aa90167291c',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M09_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M09/RIFT_M09_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeM09=data.byId.SHADE_M09;
  if(shadeM09)Object.assign(shadeM09,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M09/SHADE_M09_PRODUCTION_PILOT_V4.webp?v=25dc8bae8845ef72',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M09_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M09/SHADE_M09_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM08=data.byId.AEGIS_M08;
  if(aegisM08)Object.assign(aegisM08,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M08/AEGIS_M08_PRODUCTION_PILOT_V4.webp?v=432babf0b05cd9cd',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M08_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M08/AEGIS_M08_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM08=data.byId.EMBER_M08;
  if(emberM08)Object.assign(emberM08,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M08/EMBER_M08_PRODUCTION_PILOT_V4.webp?v=ec13f14d14846141',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M08_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M08/EMBER_M08_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM08=data.byId.BLOOM_M08;
  if(bloomM08)Object.assign(bloomM08,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M08/BLOOM_M08_PRODUCTION_PILOT_V4.webp?v=38204ecda8c93662',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M08_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M08/BLOOM_M08_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM08=data.byId.VOLT_M08;
  if(voltM08)Object.assign(voltM08,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M08/VOLT_M08_PRODUCTION_PILOT_V4.webp?v=d5a1cabf580d800c',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M08_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M08/VOLT_M08_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM08=data.byId.RIFT_M08;
  if(riftM08)Object.assign(riftM08,{
    atlas:'assets/enemies/production_pilot_v8/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V8_GPU_FINAL.webp?v=21e29dc047a5',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M08_V8_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v8/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V8_GPU_FINAL_MANIFEST.json'
  });
  const shadeM08=data.byId.SHADE_M08;
  if(shadeM08)Object.assign(shadeM08,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M08/SHADE_M08_PRODUCTION_PILOT_V4.webp?v=3ae173bc142c2431',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M08_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M08/SHADE_M08_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const aegisM07=data.byId.AEGIS_M07;
  if(aegisM07)Object.assign(aegisM07,{
    atlas:'assets/enemies/production_pilot_v4/AEGIS_M07/AEGIS_M07_PRODUCTION_PILOT_V4.webp?v=d1bb24d0aa9a417b',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'AEGIS_M07_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/AEGIS_M07/AEGIS_M07_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const emberM07=data.byId.EMBER_M07;
  if(emberM07)Object.assign(emberM07,{
    atlas:'assets/enemies/production_pilot_v4/EMBER_M07/EMBER_M07_PRODUCTION_PILOT_V4.webp?v=bc27197bedd29490',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'EMBER_M07_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/EMBER_M07/EMBER_M07_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const bloomM07=data.byId.BLOOM_M07;
  if(bloomM07)Object.assign(bloomM07,{
    atlas:'assets/enemies/production_pilot_v4/BLOOM_M07/BLOOM_M07_PRODUCTION_PILOT_V4.webp?v=8145b1b1a0554e68',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'BLOOM_M07_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/BLOOM_M07/BLOOM_M07_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const voltM07=data.byId.VOLT_M07;
  if(voltM07)Object.assign(voltM07,{
    atlas:'assets/enemies/production_pilot_v4/VOLT_M07/VOLT_M07_PRODUCTION_PILOT_V4.webp?v=12a05dbbb2099f88',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'VOLT_M07_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/VOLT_M07/VOLT_M07_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  const riftM07=data.byId.RIFT_M07;
  if(riftM07)Object.assign(riftM07,{
    atlas:'assets/enemies/production_pilot_v7/RIFT_M07/RIFT_M07_PRODUCTION_PILOT_V7_GPU_FINAL.webp?v=8cc8b959fb55',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    runtimeActive:true,
    productionRevision:'RIFT_M07_V7_GPU_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v7/RIFT_M07/RIFT_M07_PRODUCTION_PILOT_V7_GPU_FINAL_MANIFEST.json'
  });
  const shadeM07=data.byId.SHADE_M07;
  if(shadeM07)Object.assign(shadeM07,{
    atlas:'assets/enemies/production_pilot_v4/SHADE_M07/SHADE_M07_PRODUCTION_PILOT_V4.webp?v=97c064bce1c3f1d6',
    frameWidth:420,frameHeight:420,columns:6,rows:4,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ATTACK:{row:1,frames:6,fps:10,loop:false,events:{impact:3}},
      HIT:{row:2,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:3,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_FINAL',
    productionRevision:'SHADE_M07_V4_FINAL',
    sourceManifest:'assets/enemies/production_pilot_v4/SHADE_M07/SHADE_M07_PRODUCTION_PILOT_V4_MANIFEST.json'
  });
  // QA-only GPU v5 candidate.  It is deliberately opt-in and never changes
  // the normal runtime or the frozen v4 production records.
  const candidateQuery=typeof global.location?.search==='string' ? new URLSearchParams(global.location.search).get('qaEnemyAnimation') : '';
  const shadeV5=data.byId.SHADE_M01;
  if(candidateQuery==='v5-shade-m01'&&shadeV5)Object.assign(shadeV5,{
    atlas:'assets/enemies/production_pilot_v5_candidate/SHADE_M01/SHADE_M01_PRODUCTION_PILOT_V5_GPU_CANDIDATE.webp?v=fbe62abca771eedf',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'SHADE_M01_V5_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v5_candidate/SHADE_M01/SHADE_M01_PRODUCTION_PILOT_V5_GPU_CANDIDATE_MANIFEST.json'
  });
  // V6 has passed the external visual contact-sheet gate, but remains
  // QA-only until the real HTML preview is checked.  It never replaces V4
  // in a normal URL and is not marked runtime-active here.
  const shadeV6=data.byId.SHADE_M01;
  if(candidateQuery==='v6-shade-m01'&&shadeV6)Object.assign(shadeV6,{
    atlas:'assets/enemies/production_pilot_v6_candidate/SHADE_M01/SHADE_M01_PRODUCTION_PILOT_V6_GPU_CANDIDATE.webp?v=6760838c0dd7',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'SHADE_M01_V6_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v6_candidate/SHADE_M01/SHADE_M01_PRODUCTION_PILOT_V6_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M10 V6 candidate. It stays isolated from the normal V4
  // runtime until both the external visual gate and in-app gate pass.
  const riftV6=data.byId.RIFT_M10;
  if(candidateQuery==='v6-rift-m10'&&riftV6)Object.assign(riftV6,{
    atlas:'assets/enemies/production_pilot_v6_candidate/RIFT_M10/RIFT_M10_PRODUCTION_PILOT_V6_GPU_CANDIDATE.webp?v=ce9b403fa7837a6',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M10_V6_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v6_candidate/RIFT_M10/RIFT_M10_PRODUCTION_PILOT_V6_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M10 V7 candidate. It includes the external-review corrections:
  // a raised/channeled SKILL silhouette and a non-DEFEAT HIT recoil sequence.
  const riftV7=data.byId.RIFT_M10;
  if(candidateQuery==='v7-rift-m10'&&riftV7)Object.assign(riftV7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M10/RIFT_M10_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=a7c57ce7435b',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M10_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M10/RIFT_M10_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M11 V6 candidate. It is isolated until both visual gates pass.
  const riftM11V6=data.byId.RIFT_M11;
  if(candidateQuery==='v6-rift-m11'&&riftM11V6)Object.assign(riftM11V6,{
    atlas:'assets/enemies/production_pilot_v6_candidate/RIFT_M11/RIFT_M11_PRODUCTION_PILOT_V6_GPU_CANDIDATE.webp?v=70c87cf1add5',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M11_V6_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v6_candidate/RIFT_M11/RIFT_M11_PRODUCTION_PILOT_V6_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M11 V7 candidate with the same SKILL/HIT gate corrections.
  const riftM11V7=data.byId.RIFT_M11;
  if(candidateQuery==='v7-rift-m11'&&riftM11V7)Object.assign(riftM11V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M11/RIFT_M11_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=c20707cc4f1f',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M11_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M11/RIFT_M11_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M12 V7 candidate. It remains inactive until the external
  // visual gate and the real HTML runtime gate both pass.
  const riftM12V7=data.byId.RIFT_M12;
  if(candidateQuery==='v7-rift-m12'&&riftM12V7)Object.assign(riftM12V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M12/RIFT_M12_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=ef8d52e89aa9',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M12_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M12/RIFT_M12_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M13 V7 candidate with the same strict SKILL/HIT corrections.
  const riftM13V7=data.byId.RIFT_M13;
  if(candidateQuery==='v7-rift-m13'&&riftM13V7)Object.assign(riftM13V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M13/RIFT_M13_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=2bb7acb37f07',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M13_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M13/RIFT_M13_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M14 V7 candidate after the strict SKILL/HIT visual correction.
  const riftM14V7=data.byId.RIFT_M14;
  if(candidateQuery==='v7-rift-m14'&&riftM14V7)Object.assign(riftM14V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M14/RIFT_M14_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=3942426a5fa3',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M14_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M14/RIFT_M14_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M07 V6 GPU candidate.
  const riftM07V6=data.byId.RIFT_M07;
  if(candidateQuery==='v6-rift-m07'&&riftM07V6)Object.assign(riftM07V6,{
    atlas:'assets/enemies/production_pilot_v6_candidate/RIFT_M07/RIFT_M07_PRODUCTION_PILOT_V6_GPU_CANDIDATE.webp?v=8d43ffc51a83',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M07_V6_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v6_candidate/RIFT_M07/RIFT_M07_PRODUCTION_PILOT_V6_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M07 V7 candidate after the strict SKILL/HIT visual correction.
  const riftM07V7=data.byId.RIFT_M07;
  if(candidateQuery==='v7-rift-m07'&&riftM07V7)Object.assign(riftM07V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M07/RIFT_M07_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=8d43ffc51a83',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M07_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M07/RIFT_M07_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M08 V6 GPU candidate. It remains inactive until both
  // external visual review and actual in-app playback pass.
  const riftM08V6=data.byId.RIFT_M08;
  if(candidateQuery==='v6-rift-m08'&&riftM08V6)Object.assign(riftM08V6,{
    atlas:'assets/enemies/production_pilot_v6_candidate/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V6_GPU_CANDIDATE.webp?v=50195756ebaa',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M08_V6_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v6_candidate/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V6_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M08 V7 candidate after strict SKILL/HIT visual correction.
  const riftM08V7=data.byId.RIFT_M08;
  if(candidateQuery==='v7-rift-m08'&&riftM08V7)Object.assign(riftM08V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=3fac9e2437a8',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M08_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M08 V8 candidate after the second strict visual correction.
  const riftM08V8=data.byId.RIFT_M08;
  if(candidateQuery==='v8-rift-m08'&&riftM08V8)Object.assign(riftM08V8,{
    atlas:'assets/enemies/production_pilot_v8_candidate/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V8_GPU_CANDIDATE.webp?v=21e29dc047a5',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M08_V8_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v8_candidate/RIFT_M08/RIFT_M08_PRODUCTION_PILOT_V8_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M09 V6 GPU candidate. It stays inactive until the existing
  // GPT visual gate and actual in-app playback gate both pass.
  const riftM09V6=data.byId.RIFT_M09;
  if(candidateQuery==='v6-rift-m09'&&riftM09V6)Object.assign(riftM09V6,{
    atlas:'assets/enemies/production_pilot_v6_candidate/RIFT_M09/RIFT_M09_PRODUCTION_PILOT_V6_GPU_CANDIDATE.webp?v=af516a9736a4',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M09_V6_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v6_candidate/RIFT_M09/RIFT_M09_PRODUCTION_PILOT_V6_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M09 V7 candidate after the strict SKILL/HIT correction.
  const riftM09V7=data.byId.RIFT_M09;
  if(candidateQuery==='v7-rift-m09'&&riftM09V7)Object.assign(riftM09V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M09/RIFT_M09_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=7aa90167291c',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M09_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M09/RIFT_M09_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  // QA-only RIFT_M15 V7 candidate after the strict SKILL/HIT visual correction.
  const riftM15V7=data.byId.RIFT_M15;
  if(candidateQuery==='v7-rift-m15'&&riftM15V7)Object.assign(riftM15V7,{
    atlas:'assets/enemies/production_pilot_v7_candidate/RIFT_M15/RIFT_M15_PRODUCTION_PILOT_V7_GPU_CANDIDATE.webp?v=c76859b0d223',
    frameWidth:420,frameHeight:420,columns:6,rows:6,
    clips:{
      IDLE:{row:0,frames:6,fps:6,loop:true},
      ENTER:{row:1,frames:6,fps:10,loop:false},
      ATTACK:{row:2,frames:6,fps:10,loop:false,events:{impact:3}},
      SKILL:{row:3,frames:6,fps:12,loop:false,events:{impact:3}},
      HIT:{row:4,frames:6,fps:12,loop:false,events:{impact:1}},
      DEFEAT:{row:5,frames:6,fps:8,loop:false,holdLastFrame:true}
    },
    status:'PASS_ACTIVE_CANDIDATE',
    runtimeActive:false,
    productionRevision:'RIFT_M15_V7_GPU_CANDIDATE',
    sourceManifest:'assets/enemies/production_pilot_v7_candidate/RIFT_M15/RIFT_M15_PRODUCTION_PILOT_V7_GPU_CANDIDATE_MANIFEST.json'
  });
  data.version=candidateQuery==='v7-rift-m09'?'1.49.0-rift-m09-v7-gpu-candidate':candidateQuery==='v6-rift-m09'?'1.48.0-rift-m09-v6-gpu-candidate':candidateQuery==='v8-rift-m08'?'1.46.0-rift-m08-v8-gpu-candidate':candidateQuery==='v7-rift-m08'?'1.45.0-rift-m08-v7-gpu-candidate':candidateQuery==='v6-rift-m08'?'1.44.0-rift-m08-v6-gpu-candidate':candidateQuery==='v7-rift-m07'?'1.42.0-rift-m07-v7-gpu-candidate':candidateQuery==='v6-rift-m07'?'1.41.0-rift-m07-v6-gpu-candidate':candidateQuery==='v7-rift-m15'?'1.40.0-rift-m15-v7-gpu-candidate':candidateQuery==='v7-rift-m14'?'1.39.0-rift-m14-v7-gpu-candidate':candidateQuery==='v7-rift-m13'?'1.38.0-rift-m13-v7-gpu-candidate':candidateQuery==='v7-rift-m12'?'1.37.0-rift-m12-v7-gpu-candidate':candidateQuery==='v7-rift-m11'?'1.35.0-rift-m11-v7-gpu-candidate':candidateQuery==='v6-rift-m11'?'1.34.0-rift-m11-v6-gpu-candidate':candidateQuery==='v7-rift-m10'?'1.33.0-rift-m10-v7-gpu-candidate':candidateQuery==='v6-rift-m10'?'1.32.0-rift-m10-v6-gpu-candidate':candidateQuery==='v6-shade-m01'?'1.31.0-shade-v6-gpu-candidate':candidateQuery==='v5-shade-m01'?'1.30.0-shade-v5-gpu-candidate':'1.50.0-rift-m09-v7-final';
})(window);
